### ISSUE TITLE
Compiler bug: use of identical traits reports `Error [4018]`

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/core#1124] opened 2024-10-14 13:48 UTC
```
glenn@glenn-MacM2Pro ~/src/github.com/gmlewis/moonbit-gzip (master) $ moon version --all
moon 0.1.20241011 (ca50f51 2024-10-11) ~/.moon/bin/moon
moonc v0.1.20241011+9ea637707 ~/.moon/bin/moonc
moonrun 0.1.20241011 (ca50f51 2024-10-11) ~/.moon/bin/moonrun
```

EDIT: Please see _SIGNIFICANTLY BETTER_ demonstration test case in [comment below](https://github.com/moonbitlang/core/issues/1124#issuecomment-2423845682).

In [gmlewis/moonbit-flate](https://github.com/gmlewis/moonbit-flate), I have two public traits:

* [`@flate.IOReader`](https://github.com/gmlewis/moonbit-flate/blob/daee8f4826d472fe0e41b341fc201f12e562ae33/io-reader.mbt#L5-L9)
* [`@flate.IOWriter`](https://github.com/gmlewis/moonbit-flate/blob/daee8f4826d472fe0e41b341fc201f12e562ae33/io-writer.mbt#L2-L4)

In [gmlewis/moonbit-gzip](https://github.com/gmlewis/moonbit-gzip), I have two identical public traits:

* [`@gzip.IOReader`](https://github.com/gmlewis/moonbit-gzip/blob/532f5bec6768fcd4b798d31b21de48abafd68534/io-reader.mbt#L3-L7)
* [`@gzip.IOWriter`](https://github.com/gmlewis/moonbit-gzip/blob/532f5bec6768fcd4b798d31b21de48abafd68534/io-writer.mbt#L2-L4)

They should be 100% compatible.

However, when I attempt to use a `@gzip.IOReader` as a `@flate.IOReader` (or a `@gzip.IOWriter` as a `@flate.IOWriter`), the compiler says that the methods are missing. See screenshots:

![trait-bug-2-2024-10-14_09-43-36](https://github.com/user-attachments/assets/6c04d58a-19ed-48d6-8115-8a8480772ae1)
![trait-bug-1-2024-10-14_09-42-36](https://github.com/user-attachments/assets/f05e375a-7059-481a-b81f-96b0f9dc2f91)

**Comment by gmlewis** [comment] 2024-10-18 17:18
This still exists in version:

```
$ moon version --all
moon 0.1.20241017 (e833bec 2024-10-17) ~/.moon/bin/moon
moonc v0.1.20241017+e8d7befb8 ~/.moon/bin/moonc
moonrun 0.1.20241017 (e833bec 2024-10-17) ~/.moon/bin/moonrun
```

**Comment by gmlewis** [comment] 2024-10-19 13:18
Here's a better example that demonstrates this compiler bug:

Given two different traits in one package:

* [@io.Reader](https://github.com/gmlewis/moonbit-io/blob/02c4b4f123b6a5f04c14abbe3dcb13dc74a7b084/io.mbt#L88-L90)
* [@io.ByteReader](https://github.com/gmlewis/moonbit-io/blob/02c4b4f123b6a5f04c14abbe3dcb13dc74a7b084/io.mbt#L264-L266)

```rust
pub trait Reader {
  read(Self, Slice[Byte]) -> (Int, IOError?)
}

pub trait ByteReader {
  read_byte(Self) -> (Byte, IOError?)
}
```

when those two traits are combined together in a different package:

* [@flate.Reader](https://github.com/gmlewis/moonbit-flate/pull/1#pullrequestreview-2379429934)

```rust
typealias Slice[T] = @io.Slice[T]

typealias IOError = @io.IOError

pub trait Reader {
  // @io.Reader
  read(Self, Slice[Byte]) -> (Int, IOError?)
  // @io.ByteReader
  read_byte(Self) -> (Byte, IOError?)
}
```

the compiler reports `Error [4018]`:

![error-4018-2024-10-19_09-11-50](https://github.com/user-attachments/assets/16f88fea-8b63-4dec-8189-925f1c197e53)

**Comment by gmlewis** [comment] 2024-10-19 13:26
Oh, and for completeness, the `@flate.Reader` does indeed implement the `read` method here:

https://github.com/gmlewis/moonbit-flate/pull/1#pullrequestreview-2379432826

```rust
fn read(self : Decompressor, b : Slice[Byte]) -> (Int, IOError?) {
...
}
```

**Comment by Guest0x0** [comment] 2024-10-23 08:28
MoonBit's traits are not 100% structural. MoonBit allows explicit trait implementation `impl Trait for Type with f(...)`, this is useful when `Type` is not owned by you. But this also means that there are implementations that are specific to a trait's name, so traits are still nominal in MoonBit. Even if two traits have completely identical definitions, they are not the same. For example, assume `ReaderA` and `ReaderB` are traits with identical definition, the following won't work (as intended):
```rust
fn f[X : ReaderA](x : X) -> ... {
  ... use x as ReaderB ...
}
```
one should also explicitly add `ReaderB` to the bounds of `X`.

Your case here, however, is not about polymorphic function, but about trait objects. Assume `ReaderA` and `ReaderB` are identical, I think the object type `ReaderA` should indeed implement `ReaderB`. I'll fix it later in the compiler.

**Comment by gmlewis** [comment] 2024-10-31 00:00
@Guest0x0 - do you have any ETA on when the compiler will be updated with this fix?

**Comment by Guest0x0** [comment] 2024-10-31 01:54
I'll fix it before next stable release, which should be available next week

**Comment by gmlewis** [comment] 2024-10-31 02:31
> I'll fix it before next stable release, which should be available next week

Awesome, thank you, @Guest0x0 !

**Comment by Guest0x0** [comment] 2024-11-06 03:37
Should be fixed now in stable release. Re-open this if he issue persists

**Closed** 2024-11-06 03:37 UTC
